# Generated by Django 3.2.18 on 2023-03-08 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('spiritual', 'SPIRITUAl'), ('financial', 'FINANCIAL'), ('career', 'CAREER'), ('intellectual', 'INTELLECTUAL'), ('fitness', 'FITNESS'), ('social', 'SOCIAL')], max_length=25)),
                ('description', models.TextField(max_length=255)),
                ('criteria', models.TextField()),
                ('date', models.DateTimeField()),
                ('repetition', models.CharField(choices=[('never', 'NEVER'), ('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('annualy', 'ANNUALY')], default='never', max_length=25)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]